movieproject/app1/urls.py
from django.urls import path

from app1 import views

app_name='movieapp'

urlpatterns = [

    path('',views.home,name ="home"),
    path('movie/<int:movie_id>/',views.details,name="detail"),
    path('add/',views.add,name="add"),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/app1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name =models.CharField(max_length=300)
    des =models.TextField()
    year =models.IntegerField()
    img =models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/app1/forms.py
from django import forms

from app1.models import Movie

class movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','des','year','img']

movieproject/app1/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from app1.forms import movieform
from app1.models import Movie


# Create your views here.
def home(request):
    movie = Movie.objects.all()
    context ={
        'movie_list' :movie
    }
    return render(request,'home.html',context)
def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add(request):
    if request.method == "POST":
        name = request.POST.get('name',)
        des = request.POST.get('des', )
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie = Movie(name=name,des=des,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    if request.method == 'POST':
        mov=Movie.objects.get(id=id)
        form=movieform(request.POST or None, request.FILES,instance=mov)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = movieform()
    return render(request,'update.html',{'form':form})


def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container form-group">
    <form method="POST" enctype="multipart/form-data" class="form-control" style="width:300px; height:300px; padding:25px;">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Movie Name"><br>
        <input type="text" name="des" placeholder="Description"><br>
        <input type="number" name="year" placeholder="Release year"><br>
        <input type="file" name="img"><br>
        <div class="button form-group">
        <input type="submit" class="btn btn-success btn-sm" >
        </div>
    </form>
</div>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIE</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar bg-body-tertiary" >
  <div class="container-fluid">
       <a class="navbar-brand" href="/">HOME</a>
       <a class="navbar-brand" href="#">FAVOURITE MOVIES</a>
      <a class="navbar-brand" href="{% url 'movieapp:add' %}">ADD NEW</a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  are you sure?
  <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="400"height="400">
        </div>
        <div class="col-md-6">
            <h4>{{movie.name}}</h4><br>
            <h6>{{movie.des}}</h6><br>
            <h4>{{movie.year}}</h4><br>

            <a class='btn btn-warning ' href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class='btn btn-danger ' href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>




{% endblock %}

movieproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="main">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" height="250" width="250" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
<!--                <p class="card-text">{{i.des}}</p>-->
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-info">View details</a>
                </div>
            </div><br>
        </div>
        {% endfor %}
    </div>
</div>
 {% endblock %}

movieproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="form-group">
    <form method="POST" enctype="multipart/form-data" class="form-control" style="width:500px;" >
    {% csrf_token %}
      {{form.as_p }}
      <input type="submit" class="btn btn-success">
    </form>
  </div>
</div>

{% endblock %}